name: Test Build on MacOS

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install Software
        run: brew reinstall gcc # brings gfortran with it
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Print Compiler identification
        run: |
          brew ls --verbose gcc | grep gfortran
          find /opt/homebrew -name "gfortran"
          echo $PATH
          which gfortran
          gfortran --version
      - name: Build
        run: |
          cmake -B build
          cmake --build build
