name: Test Build on MacOS

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install Software
        run: |
          which gfortran
          brew install --verbose --debug gcc
          brew reinstall gcc
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build
        run: make
